/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["api_v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_auth_me_retrieve"];
        put: operations["api_v1_auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["api_v1_auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["api_v1_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_availability_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_bookings_list"];
        put?: never;
        post: operations["api_v1_bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_bookings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_bookings_calendar.ics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_bookings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_bookings_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_bookings_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_bookings_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the status of the database and Redis connections.
         */
        get: operations["api_v1_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_providers_list"];
        put?: never;
        post: operations["api_v1_providers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_providers_retrieve"];
        put: operations["api_v1_providers_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["api_v1_providers_partial_update"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/time-off/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_providers_time_off_list"];
        put?: never;
        post: operations["api_v1_providers_time_off_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/time-off/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_providers_time_off_retrieve"];
        put: operations["api_v1_providers_time_off_update"];
        post?: never;
        delete: operations["api_v1_providers_time_off_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_v1_providers_time_off_partial_update"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/working-hours/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_providers_working_hours_list"];
        put: operations["api_v1_providers_working_hours_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_services_list"];
        put?: never;
        post: operations["api_v1_services_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_services_retrieve"];
        put: operations["api_v1_services_update"];
        post?: never;
        delete: operations["api_v1_services_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_v1_services_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AvailabilityDate: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["Slot"][];
        };
        AvailabilityResponse: {
            timezone: string;
            dates: components["schemas"]["AvailabilityDate"][];
        };
        Booking: {
            readonly id: number;
            readonly customer: number;
            readonly provider: number;
            readonly service: number;
            /** Format: date-time */
            readonly start: string;
            /** Format: date-time */
            readonly end: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            readonly price_snapshot: string;
            readonly duration_snapshot: number;
            /** Format: date-time */
            readonly expires_at: string | null;
            /** Format: date-time */
            readonly submitted_at: string | null;
            readonly is_late_cancellation: boolean;
            readonly cancellation_reason: string;
            /** @default false */
            readonly has_time_off_conflict: boolean;
            readonly would_be_late_cancellation: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        BookingCreateRequest: {
            service: number;
            provider?: number | null;
            /** Format: date-time */
            start: string;
        };
        BookingDetail: {
            readonly id: number;
            readonly customer: number;
            readonly provider: number;
            readonly service: number;
            /** Format: date-time */
            readonly start: string;
            /** Format: date-time */
            readonly end: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            readonly price_snapshot: string;
            readonly duration_snapshot: number;
            /** Format: date-time */
            readonly expires_at: string | null;
            /** Format: date-time */
            readonly submitted_at: string | null;
            readonly is_late_cancellation: boolean;
            readonly cancellation_reason: string;
            /** @default false */
            readonly has_time_off_conflict: boolean;
            readonly would_be_late_cancellation: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly status_logs: components["schemas"]["BookingStatusLog"][];
        };
        BookingStatusLog: {
            readonly id: number;
            from_status?: string;
            to_status: string;
            actor?: number | null;
            reason?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        CancelBookingRequest: {
            /** @default  */
            reason: string;
        };
        EmailTokenObtainPairRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            access: string;
            refresh: string;
            user: components["schemas"]["User"];
        };
        LogoutRequest: {
            refresh: string;
        };
        PaginatedBookingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Booking"][];
        };
        PaginatedProviderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Provider"][];
        };
        PaginatedServiceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Service"][];
        };
        PaginatedTimeOffList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TimeOff"][];
        };
        PatchedProviderUpdateRequest: {
            is_active?: boolean;
            service_ids?: number[];
        };
        PatchedServiceAdminRequest: {
            name?: string;
            description?: string;
            duration_minutes?: number;
            /** Format: decimal */
            price?: string;
            buffer_minutes?: number;
        };
        PatchedTimeOffRequest: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            reason?: string;
        };
        PatchedUserRequest: {
            full_name?: string;
            timezone?: string;
        };
        Provider: {
            readonly id: number;
            readonly user: components["schemas"]["ProviderUser"];
            readonly business: number;
            readonly services: components["schemas"]["Service"][];
            readonly is_active: boolean;
        };
        ProviderCreate: {
            /** Format: email */
            email: string;
            full_name: string;
            service_ids?: number[];
        };
        ProviderCreateRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            password: string;
            service_ids?: number[];
        };
        ProviderUpdate: {
            readonly id: number;
            is_active?: boolean;
        };
        ProviderUpdateRequest: {
            is_active?: boolean;
            service_ids?: number[];
        };
        ProviderUser: {
            readonly id: number;
            /** Format: email */
            email: string;
            full_name: string;
        };
        Register: {
            readonly id: number;
            /** Format: email */
            email: string;
            full_name: string;
            timezone?: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            password: string;
            timezone?: string;
        };
        /**
         * @description * `customer` - Customer
         *     * `provider` - Provider
         *     * `admin` - Admin
         * @enum {string}
         */
        RoleEnum: "customer" | "provider" | "admin";
        Service: {
            readonly id: number;
            readonly business: number;
            name: string;
            description?: string;
            duration_minutes: number;
            /** Format: decimal */
            price: string;
            buffer_minutes?: number;
            readonly is_active: boolean;
        };
        ServiceAdmin: {
            readonly id: number;
            readonly business: number;
            name: string;
            description?: string;
            duration_minutes: number;
            /** Format: decimal */
            price: string;
            buffer_minutes?: number;
            readonly is_active: boolean;
        };
        ServiceAdminRequest: {
            name: string;
            description?: string;
            duration_minutes: number;
            /** Format: decimal */
            price: string;
            buffer_minutes?: number;
        };
        Slot: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            provider_ids: number[];
        };
        /**
         * @description * `pending` - Pending
         *     * `confirmed` - Confirmed
         *     * `cancelled` - Cancelled
         *     * `completed` - Completed
         * @enum {string}
         */
        StatusEnum: "pending" | "confirmed" | "cancelled" | "completed";
        TimeOff: {
            readonly id: number;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            reason?: string;
        };
        TimeOffRequest: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            reason?: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            full_name: string;
            readonly role: components["schemas"]["RoleEnum"];
            timezone?: string;
        };
        UserRequest: {
            full_name: string;
            timezone?: string;
        };
        WorkingHours: {
            readonly id: number;
            weekday: number;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
        };
        WorkingHoursRequest: {
            weekday: number;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["EmailTokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    api_v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    api_v1_auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    api_v1_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    api_v1_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    api_v1_availability_retrieve: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD, business timezone */
                date_from: string;
                /** @description YYYY-MM-DD, business timezone */
                date_to: string;
                /** @description Restrict to one provider */
                provider?: number;
                /** @description Service id */
                service: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
        };
    };
    api_v1_bookings_list: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                provider?: number;
                service?: number;
                /**
                 * @description * `pending` - Pending
                 *     * `confirmed` - Confirmed
                 *     * `cancelled` - Cancelled
                 *     * `completed` - Completed
                 */
                status?: "cancelled" | "completed" | "confirmed" | "pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBookingList"];
                };
            };
        };
    };
    api_v1_bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BookingCreateRequest"];
                "multipart/form-data": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    api_v1_bookings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    "api_v1_bookings_calendar.ics_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    api_v1_bookings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CancelBookingRequest"];
                "multipart/form-data": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    api_v1_bookings_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    api_v1_bookings_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    api_v1_bookings_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    api_v1_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_providers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProviderList"];
                };
            };
        };
    };
    api_v1_providers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProviderCreateRequest"];
                "multipart/form-data": components["schemas"]["ProviderCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCreate"];
                };
            };
        };
    };
    api_v1_providers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    api_v1_providers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProviderUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProviderUpdateRequest"];
                "multipart/form-data": components["schemas"]["ProviderUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUpdate"];
                };
            };
        };
    };
    api_v1_providers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProviderUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProviderUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedProviderUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUpdate"];
                };
            };
        };
    };
    api_v1_providers_time_off_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTimeOffList"];
                };
            };
        };
    };
    api_v1_providers_time_off_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeOffRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TimeOffRequest"];
                "multipart/form-data": components["schemas"]["TimeOffRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
        };
    };
    api_v1_providers_time_off_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
        };
    };
    api_v1_providers_time_off_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeOffRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TimeOffRequest"];
                "multipart/form-data": components["schemas"]["TimeOffRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
        };
    };
    api_v1_providers_time_off_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_providers_time_off_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTimeOffRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTimeOffRequest"];
                "multipart/form-data": components["schemas"]["PatchedTimeOffRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
        };
    };
    api_v1_providers_working_hours_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkingHours"][];
                };
            };
        };
    };
    api_v1_providers_working_hours_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkingHoursRequest"][];
                "application/x-www-form-urlencoded": components["schemas"]["WorkingHoursRequest"][];
                "multipart/form-data": components["schemas"]["WorkingHoursRequest"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkingHours"][];
                };
            };
        };
    };
    api_v1_services_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceList"];
                };
            };
        };
    };
    api_v1_services_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceAdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ServiceAdminRequest"];
                "multipart/form-data": components["schemas"]["ServiceAdminRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAdmin"];
                };
            };
        };
    };
    api_v1_services_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
        };
    };
    api_v1_services_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceAdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ServiceAdminRequest"];
                "multipart/form-data": components["schemas"]["ServiceAdminRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAdmin"];
                };
            };
        };
    };
    api_v1_services_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_services_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedServiceAdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedServiceAdminRequest"];
                "multipart/form-data": components["schemas"]["PatchedServiceAdminRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAdmin"];
                };
            };
        };
    };
}
