# Generated by Django 5.1.4 on 2026-09-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
    ]
