# Generated by Django 5.1.4 on 2026-09-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='catalog.provider')),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='timeoff_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='catalog.provider')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='workinghours_start_before_end'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='workinghours_weekday_range')],
            },
        ),
    ]
